stages:
  - test

test_linux_job:
  stage: test
  tags: 
    - ubuntu
  script: 
    - cd "$CI_PROJECT_DIR"
    - dotnet test
    - sh run-test.sh
  artifacts:
    paths:
      - tests/TestResults

test_windows_job:
  stage: test
  tags: 
    - windows
  script: 
    - chcp 65001
    - cd "%CI_PROJECT_DIR%"
    - dotnet test
    - call run-test.cmd
  artifacts:
    paths:
      - tests/TestResults
